#!/usr/bin/env bash
set -e

if ! [ -x "$(command -v brew)" ]; then
  echo "Homebrew missing - please install manually using instructions on https://brew.sh/"
  exit 1
fi

if ! [ -x "$(command -v ansible)" ]; then
  brew install ansible
fi

if [ "${1}" == "--bootstrap" ]; then
  if [ -f .dotfile_bootstrap_complete ]; then
    rm .dotfile_bootstrap_complete
  fi
  shift
fi

if [ -f .dotfile_bootstrap_complete ]; then
  skipargs="--skip-tags bootstrap"
fi

tags="${1}"

if [ ! -d "${HOME}/.dotfiles/roles/${tags}" ]; then
  echo "The specified tag (${tags}) doesn't exist!"
  exit 1
fi

if [ -z "${tags}" ]; then
  tags="all"
fi

ANSIBLE_CONFIG=~/.dotfiles/ansible.cfg ansible-playbook -i ~/.dotfiles/hosts ~/.dotfiles/dotfiles.yml --tags "${tags}" ${skipargs}

if command -v terminal-notifier 1>/dev/null 2>&1; then
  terminal-notifier -title "dotfiles: Bootstrap complete" -message "Successfully set up environment."
fi
