#!/usr/bin/env bash
set -e

if ! [ -x "$(command -v ansible)" ]; then
  echo "Ansible missing - please install manually:"
  echo
  echo "$ sudo pip3 install --upgrade pip"
  echo "$ pip3 install ansible"
  exit 1
fi

if [ "${1}" == "--bootstrap" ]; then
  if [ -f ${HOME}/.dotfile_bootstrap_complete ]; then
    rm ${HOME}/.dotfile_bootstrap_complete
  fi
  shift
fi

if [ -f ${HOME}/.dotfile_bootstrap_complete ]; then
  skipargs="--skip-tags bootstrap"
fi

tags="${1}"

if [ ! -d "${HOME}/.dotfiles/roles/${tags}" ]; then
  echo "The specified tag (${tags}) doesn't exist!"
  exit 1
fi

if [ -z "${tags}" ]; then
  tags="all"
fi

ANSIBLE_CONFIG=~/.dotfiles/ansible.cfg ansible-galaxy install -r ~/.dotfiles/requirements.yml &>/dev/null
ANSIBLE_CONFIG=~/.dotfiles/ansible.cfg ansible-playbook ~/.dotfiles/dotfiles.yml --ask-become-pass --tags "${tags}" ${skipargs}

if command -v terminal-notifier 1>/dev/null 2>&1; then
  terminal-notifier -title "dotfiles: Bootstrap complete" -message "Successfully set up environment."
fi
