---
- name: Set up local workstation
  hosts: local

  vars_files: ["config.defaults.yml"]

  pre_tasks:
    - name: "[󰆍 dotfiles] Include config.yml overrides"
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob: "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ["brew"]

    - role: brew
      tags: ["brew"]

    - role: dotfiles
      tags: ["dotfiles"]

    - role: gem
      tags: ["gem"]

    - role: bun
      tags: ["bun"]

    - role: mas
      tags: ["mas"]

    - role: macos
      tags: ["macos"]

    - role: ghostty
      tags: ["ghostty"]

    - role: uv
      tags: ["uv"]

    - role: docker
      tags: ["docker"]
