#!/usr/bin/env bash

# Check if bork repo exists
if [ ! -d bork/.git ]; then
    git clone https://github.com/mattly/bork.git
fi

COMMAND="satisfy"

# Check arguments
if [ -z ${1} ]; then
    # Make sure dotfile repo is up to date
    git pull
    # If no 2nd argument => use bootstrap borkfile
    bork/bin/bork ${COMMAND} borkfiles/bootstrap.bork
else
    # Make sure dotfile repo is up to date
    git pull
    # Otherwise, install use the specific borkfile(s)
    BORKFILES=${@:1}
    # For each specified borkfile
    for BORK in ${BORKFILES}; do
        if [[ -f borkfiles/${BORK}.bork ]]; then
            # Expand to actual path of borkfile, append to $BORKFILESTRING
            BORKFILESTRING+=" borkfiles/${BORK}.bork"
        else 
            echo "Error: couldn't find borkfile \"borkfiles/${BORK}.bork\""
        fi
    done
    # Check if we have found at least one valid borkfile
    if [[ -z ${BORKFILESTRING} ]]; then
        echo "Error: no valid borkfiles to process!"
    else
        # Execute $BORKFILESTRING 
        bork/bin/bork ${COMMAND} ${BORKFILESTRING}
    fi
fi