# Enable mouse support
set -g mouse on

# Begin to count from 1
set -g base-index 1

# Bind CTRL+k to clear window
bind -n C-k clear-history

# Bind ALT + Arrow keys to switch to next/previous window
bind-key -n M-Right next-window
bind-key -n M-Left previous-window

# Activity indicator
set -g monitor-activity on
set -g visual-activity off

set-option -g set-titles on
set-option -g set-titles-string '#T'
