" be iMproved
set nocompatible
filetype off

"""
" General
"""

syntax enable                     " Enable syntax highlighting
set clipboard=unnamed             " Use OS X clipboard
set autoread                      " Auro reload on local changes
set nowritebackup                 " Disable backups
set noswapfile                    " Disable swap files
set history=999                   " Set history

set backspace=indent,eol,start    " Usual backspace behaviour

set shortmess+=I                  " Disable splash screen
set ruler                         " Show cursor position (if powerline is not loaded)
set cursorline                    " Highlight current line
set noerrorbells                  " Disable possible error messages
set ttyfast                       " Fast terminal connection
set hlsearch                      " Highlight search results
set ignorecase                    " Ignore cases ...
set smartcase                     " ... unless there is a capital letter
set incsearch                     " Display incremental searches
set relativenumber                " Relative line numbers
set numberwidth=4                 " Four columns for line numbers
set tabstop=2                     " Soft tabs, 2 characters
set softtabstop=2                 " "
set shiftwidth=2                  " "
set expandtab                     " "

"""
" Vundle
"""

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

" let Vundle manage Vundle
Plugin 'gmarik/Vundle.vim'

" vim-markdown (https://github.com/tpope/vim-markdown)
Plugin 'tpope/vim-markdown'

" All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on

"""
" Plugin settings
"""

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
