###
### GPG
###

if [ -f "${HOME}/.gnupg/gpg-agent-info" ]; then
  . "${HOME}/.gnupg/gpg-agent-info"
  export SSH_AUTH_SOCK
  export GPG_TTY=$(tty)
  export GPG_AGENT_INFO
fi

###
### Exports (php-fpm, maven and $PATH)
###

# Yellow (temp) autosuggested string
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3"

# Go
export GOPATH=$HOME/.go

# Set dev.sh (https://github.com/frdmn/dev-sh) project path
export devsearch_projectspath="${HOME}/Development"

# $EDITOR
export EDITOR="vim"

# Gem Home dir
export GEM_HOME="$HOME/.gem"

# Update locale
export LANG="de_DE.UTF-8"
