###
### GPG
###

export GPG_TTY=$TTY
export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"

###
### Exports
###

# Go
export GOPATH=$HOME/.go

# Set dev.sh (https://github.com/frdmn/dev-sh) project path
export devsearch_projectspath="${HOME}/Development"

# $EDITOR
export EDITOR="vim"

# Gem Home dir
export GEM_HOME="$HOME/.gem"

# Update locale
export LANG="de_DE.UTF-8"

# uv
export PATH="${HOME}/.local/bin:$PATH"

# bun
export BUN_INSTALL="${HOME}/.bun"
export PATH="${BUN_INSTALL}/bin:$PATH"
