###
### User configuration
###

# General
setopt interactivecomments     # Comments in interactive shell
setopt auto_cd                 # Just typing the directory name cd's into it
setopt auto_menu               # Use menu completion after the second completion request
setopt complete_in_word        # Only complete when completion is confirmed
setopt correct                 # Try to autocorrect command
setopt multios                 # Allow multiple input/output redirection
setopt autopushd               # Makes cd, pushd (cd +1, cd -1)
setopt prompt_subst            # Enable parameter expansion, command substitution, etc.
setopt prompt_cr               # prompt always at beginning of line
setopt auto_param_slash        # If a parameter is completed whose content is the name of a directory, then add a trailing slash
setopt mail_warning            # Print a warning message if a mail file has been accessed since the shell last checked
setopt nonomatch               # Escape URL's special chars (eg.: ?)
setopt no_list_beep            # Don't beep on an ambiguous completion
unsetopt menu_complete         # Dont insert completion results immedietly
unsetopt beep                  # Don't beep
unsetopt correct_all           # Don't try to autocorrect all arguments

# History

setopt append_history          # Append history to existing file
setopt extended_history        # Store timestamp and runtime
setopt share_history           # Always import new commands from $HISTFILE
setopt hist_expire_dups_first  # Expire duplicate history entries first
setopt hist_ignore_dups        # Don't save entries if they are dupes of the previous event
setopt hist_ignore_space       # If command starts with a space, don't append to history
setopt hist_find_no_dups       # Don't cycle through dupes
setopt hist_reduce_blanks      # Trim multiple blanks in history

SAVEHIST=999999
HISTSIZE=999999
CASE_SENSITIVE="false"

HISTFILE=~/.zsh_history

###
### General
###

# Use emacs mode
bindkey -e

# Enable colors
autoload -U colors && colors

###
### Plugins and prompt
###

# Optional folder to load static zsh completions from
fpath=(~/.zsh/completions $fpath)

# Source antidote
source ${HOMEBREW_PREFIX:-/opt/homebrew}/opt/antidote/share/antidote/antidote.zsh

# Initialize plugins from .zsh_plugins.txt
antidote load

###
### Aliases and functions
###

# Load aliases and functions
. ~/.zsh_aliases
. ~/.zsh_functions

###
### Key bindings
### (To find out the actual bindings, use Ctrl+V followed by the key in a zsh shell)
###

# Skip forward/back a word with opt-arrow
bindkey '[D' backward-word
bindkey '[C' forward-word

# Make the delete key (or Fn + Delete on the Mac) work instead of outputting a ~
bindkey '^?' backward-delete-char
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char
bindkey "\e[3~" delete-char

# bind P and N for EMACS mode
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# OS X support
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

###
### Prompt
###

# Single line prompt
prompt_newline='%666v'
PROMPT=" $PROMPT"

# Autosuggested strings in yellow, instead of default grey
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3"
