---
- name: "[﬒ dotfiles] Get list of files to symlink"
  ansible.builtin.shell: |
    ls -1 {{ playbook_dir }}/files/dotfiles > /tmp/dotfilesToLink
  changed_when: false

- name: "[ dotfiles] Store list of files into variable"
  ansible.builtin.command: "cat /tmp/dotfilesToLink"
  register: files_to_symlink
  changed_when: false
  tags:
    - skip_ansible_lint

- name: "[ dotfiles] Set symlinks"
  ansible.builtin.file:
    src: '{{ playbook_dir }}/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  with_items:
    - "{{ files_to_symlink.stdout_lines }}"

- name: "[ dotfiles] Download vim-plug (VIm plugin manager)"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
    mode: "0644"
  changed_when: false

- name: "[ dotfiles] Remove legacy Vundle installation"
  ansible.builtin.file:
    path: ~/.vim/bundle
    state: absent

- name: "[ dotfiles] Setup and install VIm plugins"
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail &&
      echo | echo | vim '+PlugInstall --sync' +qall &>/dev/null
  args:
    executable: /bin/bash
  changed_when: false
