---
- name: "[ macOS] Set macOS defaults"
  community.general.osx_defaults:
    domain: "{{ item.domain | default('NSGlobalDomain') }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop_control:
    label: "{{ item.key }}"
  loop:
    # Disable smart quotes/dashes as they're annoying when typing code
    - key: NSAutomaticQuoteSubstitutionEnabled
      type: bool
      value: false
    - key: NSAutomaticDashSubstitutionEnabled
      type: bool
      value: false
    # Trackpad: enable tap to click for user and login screen
    - key: com.apple.mouse.tapBehavior
      type: integer
      value: 1
    - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
      key: Clicking
      type: integer
      value: 1
    # Disable press-and-hold for keys in favor of key repeat
    - key: ApplePressAndHoldEnabled
      type: bool
      value: false
    # Blazingly fast keyboard repeat rate with a short delay
    - key: KeyRepeat
      type: integer
      value: 2
    - key: InitialKeyRepeat
      type: integer
      value: 15
    # Increase speed of trackpad cursor movement
    - key: com.apple.trackpad.scaling
      type: float
      value: 3
