---
- name: "[ homebrew] Configure Homebrew taps"
  community.general.homebrew_tap:
    name: "{{ item }}"
  loop: "{{ brew_taps }}"

- name: "[ homebrew] Install Homebrew formulae"
  community.general.homebrew:
    name: "{{ item }}"
  loop: "{{ brew_packages }}"

- name: "[ homebrew] Install Homebrew casks"
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ cask_packages }}"
