" be iMproved
set nocompatible
filetype off

" Enable syntax highlighting
syntax enable

"""
" Vundle
"""

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

" let Vundle manage Vundle
Plugin 'gmarik/Vundle.vim'

" Powerline (https://github.com/powerline/powerline)
Bundle 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
" Syntax checker (https://github.com/scrooloose/syntastic)
Plugin 'Syntastic'
" YouCompleteMe (https://github.com/Valloric/YouCompleteMe)
Plugin 'Valloric/YouCompleteMe'
" vim-markdown (https://github.com/tpope/vim-markdown)
Plugin 'tpope/vim-markdown'

" All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on

"""
" Plugin settings
"""

" [Powerline] Always show powerline
set laststatus=2

" [Powerline] Use 256 colours
set t_Co=256

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Tomorrow-Night-Eighties theme
colorscheme Tomorrow-Night-Eighties
