" Load powerline
set rtp+=/usr/local/lib/python2.7/site-packages/powerline/bindings/vim/

" Always show powerline
set laststatus=2

" Use 256 colours (Use this setting only if your terminal supports 256 colours)
set t_Co=256
