###
### GPG
###

if [ -f "${HOME}/.gnupg/gpg-agent-info" ]; then
  . "${HOME}/.gnupg/gpg-agent-info"
  export SSH_AUTH_SOCK
  export GPG_TTY=$(tty)
  export GPG_AGENT_INFO
fi

###
### Exports (php-fpm, maven and $PATH)
###

# Yellow (temp) autosuggested string
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3"

# php-fpm
export PHP_AUTOCONF="/usr/local/bin/autoconf"
#export PATH="$(brew --prefix homebrew/php/php55)/bin:$PATH"

# Maven
export JAVA_HOME=$(/usr/libexec/java_home)

# Go
export GOPATH=$HOME/.go
export PATH=$PATH:/usr/local/opt/go/libexec/bin

# Set dev.sh (https://github.com/frdmn/dev-sh) project path
export devsearch_projectspath="${HOME}/Development"

# Set pssh configuration directory
export psshrun_configpath="${HOME}/.pssh"

# $PATH
export PATH=$HOME/.bin:/usr/local/sbin:/usr/local/bin:$HOME/.composer/vendor/bin:$PATH:$HOME/.npm-packages/bin
export EDITOR="vim"

# Make sure to export docker-machine env variables
#[[ $(docker-machine ls -q --filter "state=Running") ]] && eval $(docker-machine env default)
