###
### User configuration
###

# General
setopt interactivecomments     # Comments in interactive shell
setopt auto_cd                 # Just typing the directory name cd's into it
setopt auto_menu               # Use menu completion after the second completion request
setopt complete_in_word        # Only complete when completion is confirmed
setopt correct                 # Try to autocorrect command
setopt multios                 # Allow multiple input/output redirection
setopt autopushd               # Makes cd, pushd (cd +1, cd -1)
setopt prompt_subst            # Enable parameter expansion, command substitution, etc.
setopt prompt_cr               # prompt always at beginning of line
setopt auto_param_slash        # If a parameter is completed whose content is the name of a directory, then add a trailing slash
setopt mail_warning            # Print a warning message if a mail file has been accessed since the shell last checked
setopt nonomatch               # Escape URL's special chars (eg.: ?)
setopt no_list_beep            # Don't beep on an ambiguous completion
unsetopt menu_complete         # Dont insert completion results immedietly
unsetopt beep                  # Don't beep
unsetopt correct_all           # Don't try to autocorrect all arguments

# History

setopt append_history          # Append history to existing file
setopt inc_append_history      # Append every single command to $HISTFILE immediately after hitting ENTER
setopt extended_history        # Store timestamp and runtime
setopt share_history           # Always import new commands from $HISTFILE
setopt hist_expire_dups_first  # Expire duplicate history entries first
setopt hist_ignore_dups        # Don't save entries if they are dupes of the previous event
setopt hist_ignore_space       # If command starts with a space, don't append to history
setopt hist_find_no_dups       # Don't cycle through dupes
setopt hist_reduce_blanks      # Trim multiple blanks in history

SAVEHIST=999999
HISTSIZE=999999
CASE_SENSITIVE="false"

HISTFILE=~/.zsh_history

###
### General
###

# Use emacs mode
bindkey -e

# Enable colors
autoload -U colors && colors

# Add functions folder in $fpath array
fpath=( $fpath $HOME/.zsh/functions )

###
### Auto/tab-completions
###

# Enable bash completion
autoload bashcompinit && bashcompinit

# Proper case insensitivity
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Use proper completion
autoload -U compinit && compinit
zstyle ':completion:*' menu select

# Add autocomplete for git-extras
zstyle ':completion:::git:*' script /usr/local/etc/bash_completion.d/git-completion.bash

# Don't complete uninteresting users
zstyle ':completion:*:*:*:users' ignored-patterns \
        adm amanda apache avahi beaglidx bin cacti canna clamav daemon \
        dbus distcache dovecot fax ftp games gdm gkrellmd gopher \
        hacluster haldaemon halt hsqldb ident junkbust ldap lp mail \
        mailman mailnull mldonkey mysql nagios \
        named netdump news nfsnobody nobody nscd ntp nut nx openvpn \
        operator pcap postfix postgres privoxy pulse pvm quagga radvd \
        rpc rpcuser rpm shutdown squid sshd sync uucp vcsa xfs

# Disable tab character insertion
zstyle ':completion:*' insert-tab false

###
### Plugins and prompt
###

# Load Robby Russell's theme/prompt and dependencies
. ${HOME}/.zsh/appearance.zsh
. ${HOME}/.zsh/git.zsh
. ${HOME}/.zsh/git-extras.zsh
. ${HOME}/.zsh/prompts/robbyrussell.zsh

# Load zsh-syntax-highlighting plugin
. ${HOME}/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Load zsh-history-substring-search
. ${HOME}/.zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# Load zsh-autosuggestions plugin
. ${HOME}/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Load zsh-notify plugin
. ${HOME}/.zsh/plugins/zsh-notify/notify.plugin.zsh

# Complete known SSH hosts
. ${HOME}/.zsh/ssh-hosts.zsh

###
### Aliases and functions
###

# Load bash/zsh shared aliases and functions
. ~/.sh_aliases
. ~/.sh_functions

# Load zsh specific functions
. ~/.zsh_functions

if [ -f ${HOME}/.bash_vault ]; then
  . ${HOME}/.bash_vault
fi

# Make sure to export docker-machine env variables
[[ $(docker-machine ls -q --filter "state=Running") ]] && eval $(docker-machine env default)

###
### Key bindings
### (To find out the actual bindings, use Ctrl+V followed by the key in a zsh shell)
###

## General
# Skip forward/back a word with opt-arrow
bindkey '[D' backward-word
bindkey '[C' forward-word

# Skip to start/end of line with opt-shift-arrow
bindkey '^[[1;10D' beginning-of-line
bindkey '^[[1;10C' end-of-line

# Make the delete key (or Fn + Delete on the Mac) work instead of outputting a ~
bindkey '^?' backward-delete-char
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char
bindkey "\e[3~" delete-char

## zsh-autosuggestions
# use ctrl+t to toggle autosuggestions
bindkey '^T' autosuggest-toggle

## zsh-history-substring-search
# bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# bind P and N for EMACS mode
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# OS X support
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

###
### Per hostname
###

# Check for host specific sources/includes
FULLHOST=$(hostname -f)
if [ "$(ls ${HOME}/.dotfiles/hostnames/${FULLHOST}/includes 2> /dev/null)" ]; then
  for file in ${HOME}/.dotfiles/hostnames/${FULLHOST}/includes/*; do
    . "${file}"
  done
fi

###
### Exports (php-fpm, maven and $PATH)
###

# Yellow (temp) autosuggested string
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3"

# php-fpm
export PHP_AUTOCONF="/usr/local/bin/autoconf"
#export PATH="$(brew --prefix homebrew/php/php55)/bin:$PATH"

# Maven
export JAVA_HOME=$(/usr/libexec/java_home)

# Go
export GOPATH=$HOME/.go
export PATH=$PATH:/usr/local/opt/go/libexec/bin

# Set dev.sh (https://github.com/frdmn/dev-sh) project path
export devsearch_projectspath="${HOME}/Development"

# Set pssh configuration directory
export psshrun_configpath="${HOME}/.pssh"

# $PATH
export PATH=$HOME/.bin:/usr/local/sbin:/usr/local/bin:$HOME/.composer/vendor/bin:$PATH:$HOME/.npm-packages/bin
export EDITOR="vim"
