###
### User configuration
###

# General
setopt no_beep
setopt interactive_comments
setopt auto_cd
setopt cdablevars
setopt pushd_ignore_dups
setopt extended_glob
setopt always_to_end
setopt auto_menu
setopt auto_name_dirs
setopt complete_in_word
unsetopt menu_complete
unsetopt correct_all
setopt correct
setopt prompt_subst
setopt multios

# History
setopt append_history
setopt extended_history
setopt inc_append_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_find_no_dups
setopt hist_reduce_blanks
setopt hist_verify
setopt share_history

SAVEHIST=5000
HISTFILE=~/.zsh_history

###
### General
###

# Enable bash completion
autoload bashcompinit && bashcompinit

# Enable colors
autoload -U colors && colors

# Use proper completion
autoload -U compinit && compinit
zstyle ':completion:*' menu select

# Load bash aliases and zsh functions
. ~/.bash_aliases
. ~/.zsh_functions

complete -o nospace -o filenames -F dev

###
### Plugins and prompt
###

# Load Robby Russell's theme/prompt and dependencies
. ${HOME}/.zsh/git.zsh
. ${HOME}/.zsh/appearance.zsh
. ${HOME}/.zsh/prompts/robbyrussell.zsh

# Load zsh-syntax-highlighting plugin
. ${HOME}/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Load tmuxinator completion
. ${HOME}/.zsh/tmuxinator.zsh

# Load dotfiles ZSH function to use without being in $PATH
. ${HOME}/.zsh/dotfiles.zsh

###
### Key bindings
### (To find out the actual bindings, use Ctrl+V followed by the key in a zsh shell)
###

# Skip forward/back a word with opt-arrow
bindkey '[D' backward-word
bindkey '[C' forward-word

# Skip to start/end of line with opt-shift-arrow
bindkey '^[[1;10D' beginning-of-line
bindkey '^[[1;10C' end-of-line

# Make the delete key (or Fn + Delete on the Mac) work instead of outputting a ~
bindkey '^?' backward-delete-char
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char
bindkey "\e[3~" delete-char

###
### Exports (php-fpm, maven and $PATH)
###

# php-fpm
export PATH="$(brew --prefix homebrew/php/php55)/bin:$PATH"

# Maven
export JAVA_HOME=$(/usr/libexec/java_home)

# Go
export GOPATH=$HOME/.go
export PATH=$PATH:/usr/local/opt/go/libexec/bin

# Set dev.sh (https://github.com/frdmn/dev-sh) project path
export devsearch_projectspath="${HOME}/Dropbox/Share/Development"

# Set pssh configuration directory
export psshrun_configpath="${HOME}/.pssh"

# $PATH
export PATH=$HOME/.bin:/usr/local/sbin:/usr/local/bin:$PATH
