---
# yamllint disable
name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - feature/test

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Run yamllint
        uses: karancode/yamllint-github-action@master

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-12
          - macos-11

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - name: Install Ansible using Homebrew
        run: brew install ansible

      - name: Test the playbook's syntax
        run: ansible-playbook dotfiles.yml --syntax-check

      - name: Test the playbook
        run: ansible-playbook dotfiles.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook dotfiles.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: '1'
